name: Generate Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  template:
    name: Template generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute template
        run: |
          cookiecutter . --no-input

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Run make commands
        run: |
          cd my_repo
          make requirements
          make dev_requirements
          make clean
          make data
          make help
        env:
          TERM: xterm

      - name: Build documentation
        run: |
          cd my_repo
          make build_documentation

      - name: Test dockerfiles
        run: |
          cd my_repo
          docker compose build